name: Release
on: push
jobs:
  release:
    name: Updates languages, releases a new version if needed
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Install Node
        id: install_node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - name: Update
        id: update
        run: |
          npm run update
      - name: Test
        id: test
        if: ${{ steps.build.update.status == 'updated' }}
        run: |
          npm run test
      - name: Release
        id: release
        if: ${{ steps.build.update.status == 'updated' }}
        run: |
          npm run release
        with:
          github_token: ${{ secrets.NPM_TOKEN }}
          test: "test"
      # - name: Publish
      #   id: publish
      #   if: ${{ steps.build.update.status == 'updated' }}
      #   run: |
      #     npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}